name: Création fork
on:
  workflow_dispatch:
    inputs:
      machine_number:
        description: 'Numéro machine'
        default: '000'
        required: true
      client_name:
        description: "Nom client (attention, pas d'espaces)"
        default: ''
        required: true
      case_number:
        description: 'Numéro affaire'
        default: 'UN22_'
        required: true

jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
    - name: Fork le repository en POST
      env:
        GH_TOKEN: ${{ secrets.TOKEN_POUR_FORK }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/davidroulin/training/forks \
          -f name="training-2-autofork"
          -F default_branch_only=false
